using Templar.Rendering;
using Templar.Presets;
using Xunit;

namespace Templar.Tests;

public class CSharpFileTests
{
    [Fact]
    public void RendersHeaderUsingsNamespaceBody()
    {
        var file = new CSharpFile
        {
            Namespace = "Acme.Generated",
            Usings = new[] { "System", "System.Linq" },
            Body = "public sealed class Foo;"
        };

        var output = file.Render();

        Assert.Contains("#nullable enable", output);
        Assert.Contains("using System;", output);
        Assert.Contains("using System.Linq;", output);
        Assert.Contains("namespace Acme.Generated;", output);
        Assert.Contains("public sealed class Foo;", output);
    }

    [Fact]
    public void EmptyUsingsRendersBlankBlock()
    {
        var file = new CSharpFile
        {
            Namespace = "Empty",
            Body = "// nothing"
        };

        var output = file.Render();

        Assert.DoesNotContain("using ", output);
        Assert.Contains("namespace Empty;", output);
    }

    [Fact]
    public void PragmasEmittedBetweenHeaderAndUsings()
    {
        var file = new CSharpFile
        {
            Namespace = "X",
            Pragmas = "#pragma warning disable CS8618",
            Usings = new[] { "System" },
            Body = "class C;"
        };

        var output = file.Render();
        var pragmaIdx = output.IndexOf("#pragma warning");
        var usingIdx = output.IndexOf("using System;");
        var nsIdx = output.IndexOf("namespace X;");

        Assert.True(pragmaIdx > 0);
        Assert.True(pragmaIdx < usingIdx, "pragmas come before usings");
        Assert.True(usingIdx < nsIdx, "usings come before namespace");
    }

    [Fact]
    public void CustomHeaderOverridesDefault()
    {
        var file = new CSharpFile
        {
            Header = "// CUSTOM HEADER",
            Namespace = "X",
            Body = "class C;"
        };

        var output = file.Render();
        Assert.Contains("// CUSTOM HEADER", output);
        Assert.DoesNotContain("<auto-generated", output);
    }

    private sealed class DerivedCSharpFile : CSharpFile
    {
        public string ExtraBlock { get; init; } = "";

        // Provide a Body that references the extra property.
        public override string Body { get; init; } = "// will be overridden in inline-init below";
    }

    [Fact]
    public void SubclassWithExtraBindingWorks()
    {
        var file = new DerivedCSharpFile
        {
            Namespace = "Subclassed",
            Usings = new[] { "System" },
            ExtraBlock = "// extra goes here",
            Body = "class Foo { /* {{ extraBlock }} */ }"
        };

        // Note: extra-block must be inserted by the body itself for this
        // simple test; the goal is just that subclass-added properties
        // auto-bind without ceremony.
        var output = file.Render();
        Assert.Contains("namespace Subclassed;", output);
        Assert.Contains("class Foo", output);
    }
}
